version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: hack
      POSTGRES_PASSWORD: hack
      POSTGRES_DB: hack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - default

volumes:
  postgres_data: