# Generated by Django 5.2.1 on 2025-05-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='video',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
