# Generated by Django 5.2.1 on 2025-05-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
