# Generated by Django 5.2.1 on 2025-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_playlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='quiz_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
